name: 'poc-alelo'

services:
  rabbitmq:
    image: rabbitmq:3.13.6-management-alpine
    restart: no
    container_name: 'rabbitmq_alelo'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512MB'